BEGIN;
CREATE SCHEMA app;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE FUNCTION app.org_id() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('app.org_id',true),'')::uuid $$;
CREATE FUNCTION app.actor_id() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('app.user_id',true),'')::uuid $$;
CREATE TABLE app.organizations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL CHECK(length(name) BETWEEN 1 AND 200),timezone text NOT NULL DEFAULT 'Asia/Tokyo',settings jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app.users(id uuid PRIMARY KEY,display_name text NOT NULL, email text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE app.memberships(org_id uuid NOT NULL REFERENCES app.organizations,id uuid NOT NULL REFERENCES app.users,role text NOT NULL CHECK(role IN ('admin','teacher','student')),active boolean NOT NULL DEFAULT true,PRIMARY KEY(org_id,id));
CREATE TABLE app.teacher_profiles(org_id uuid NOT NULL,id uuid NOT NULL,teacher_number text NOT NULL,kana text NOT NULL DEFAULT '',department_name text NOT NULL DEFAULT '',specialties jsonb NOT NULL DEFAULT '[]',availability jsonb NOT NULL DEFAULT '{}',row_version int NOT NULL DEFAULT 1,PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,id) REFERENCES app.memberships,UNIQUE(org_id,teacher_number));
CREATE TABLE app.classrooms(org_id uuid NOT NULL REFERENCES app.organizations,id uuid NOT NULL DEFAULT gen_random_uuid(),name text NOT NULL,capacity int NOT NULL CHECK(capacity>0),starts_on date NOT NULL,ends_on date NOT NULL,archived boolean NOT NULL DEFAULT false,row_version int NOT NULL DEFAULT 1,PRIMARY KEY(org_id,id),CHECK(ends_on>=starts_on),UNIQUE(org_id,name,starts_on));
CREATE TABLE app.classroom_teachers(org_id uuid NOT NULL,classroom_id uuid NOT NULL,teacher_id uuid NOT NULL,is_primary boolean NOT NULL DEFAULT false,PRIMARY KEY(org_id,classroom_id,teacher_id),FOREIGN KEY(org_id,classroom_id) REFERENCES app.classrooms,FOREIGN KEY(org_id,teacher_id) REFERENCES app.teacher_profiles);
CREATE UNIQUE INDEX classroom_primary_teacher ON app.classroom_teachers(org_id,classroom_id) WHERE is_primary;
CREATE TABLE app.student_profiles(org_id uuid NOT NULL,id uuid NOT NULL,employee_number text NOT NULL,kana text NOT NULL DEFAULT '',company_name text NOT NULL DEFAULT '',department_name text NOT NULL,joined_on date NOT NULL,classroom_id uuid NOT NULL,teacher_id uuid NOT NULL,training_starts_on date NOT NULL,training_due_on date NOT NULL,active boolean NOT NULL DEFAULT true,row_version int NOT NULL DEFAULT 1,PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,id) REFERENCES app.memberships,FOREIGN KEY(org_id,classroom_id,teacher_id) REFERENCES app.classroom_teachers(org_id,classroom_id,teacher_id),UNIQUE(org_id,employee_number),CHECK(training_due_on>=training_starts_on));
CREATE TABLE app.programs(org_id uuid NOT NULL REFERENCES app.organizations,id uuid NOT NULL DEFAULT gen_random_uuid(),name text NOT NULL,description text NOT NULL DEFAULT '',department_name text NOT NULL DEFAULT '',archived boolean NOT NULL DEFAULT false,PRIMARY KEY(org_id,id));
CREATE TABLE app.program_versions(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),program_id uuid NOT NULL,version_number int NOT NULL CHECK(version_number>0),state text NOT NULL CHECK(state IN ('draft','published','archived')),published_at timestamptz,policy jsonb NOT NULL DEFAULT '{}',PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,program_id) REFERENCES app.programs,UNIQUE(org_id,program_id,version_number));
CREATE TABLE app.units(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),program_version_id uuid NOT NULL,title text NOT NULL,position int NOT NULL CHECK(position>=0),required boolean NOT NULL DEFAULT true,weight numeric(10,2) NOT NULL CHECK(weight>0),pass_score numeric(5,2) CHECK(pass_score BETWEEN 0 AND 100),required_attendance boolean NOT NULL DEFAULT false,requires_review boolean NOT NULL DEFAULT false,PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,program_version_id) REFERENCES app.program_versions,UNIQUE(org_id,program_version_id,position),UNIQUE(org_id,program_version_id,id));
CREATE TABLE app.materials(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),unit_id uuid NOT NULL,title text NOT NULL,kind text NOT NULL CHECK(kind IN ('pdf','video','image','link','quiz','assignment')),object_key text,external_url text,scan_state text NOT NULL CHECK(scan_state IN ('pending','clean','blocked','not_applicable')),published boolean NOT NULL DEFAULT false,required boolean NOT NULL DEFAULT true,size_bytes bigint CHECK(size_bytes>=0),PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,unit_id) REFERENCES app.units,CHECK(NOT published OR scan_state IN ('clean','not_applicable')),CHECK(external_url IS NULL OR external_url LIKE 'https://%'));
CREATE TABLE app.classroom_programs(org_id uuid NOT NULL,classroom_id uuid NOT NULL,program_version_id uuid NOT NULL,PRIMARY KEY(org_id,classroom_id,program_version_id),FOREIGN KEY(org_id,classroom_id) REFERENCES app.classrooms,FOREIGN KEY(org_id,program_version_id) REFERENCES app.program_versions);
CREATE TABLE app.enrollments(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),student_id uuid NOT NULL,program_version_id uuid NOT NULL,due_on date NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(org_id,id),UNIQUE(org_id,id,program_version_id),FOREIGN KEY(org_id,student_id) REFERENCES app.student_profiles,FOREIGN KEY(org_id,program_version_id) REFERENCES app.program_versions,UNIQUE(org_id,student_id,program_version_id));
CREATE TABLE app.unit_progress(org_id uuid NOT NULL,enrollment_id uuid NOT NULL,program_version_id uuid NOT NULL,unit_id uuid NOT NULL,state text NOT NULL CHECK(state IN ('not_started','in_progress','review_pending','completed')),completed_at timestamptz,row_version int NOT NULL DEFAULT 1,PRIMARY KEY(org_id,enrollment_id,unit_id),FOREIGN KEY(org_id,enrollment_id,program_version_id) REFERENCES app.enrollments(org_id,id,program_version_id),FOREIGN KEY(org_id,program_version_id,unit_id) REFERENCES app.units(org_id,program_version_id,id),CHECK((state='completed')=(completed_at IS NOT NULL)));
CREATE TABLE app.material_receipts(org_id uuid NOT NULL,student_id uuid NOT NULL,material_id uuid NOT NULL,confirmed_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(org_id,student_id,material_id),FOREIGN KEY(org_id,student_id) REFERENCES app.student_profiles,FOREIGN KEY(org_id,material_id) REFERENCES app.materials);
CREATE TABLE app.quiz_questions(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),material_id uuid NOT NULL,prompt text NOT NULL,choices jsonb NOT NULL,answer_key jsonb NOT NULL,points numeric NOT NULL CHECK(points>0),PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,material_id) REFERENCES app.materials);
CREATE TABLE app.quiz_attempts(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),material_id uuid NOT NULL,student_id uuid NOT NULL,answers jsonb NOT NULL,score numeric CHECK(score BETWEEN 0 AND 100),submitted_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,material_id) REFERENCES app.materials,FOREIGN KEY(org_id,student_id) REFERENCES app.student_profiles);
CREATE TABLE app.submissions(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),material_id uuid NOT NULL,student_id uuid NOT NULL,body text NOT NULL DEFAULT '',object_key text,scan_state text NOT NULL DEFAULT 'pending' CHECK(scan_state IN ('pending','clean','blocked','not_applicable')),state text NOT NULL CHECK(state IN ('submitted','accepted','revision_requested')),reviewer_id uuid,feedback text,submitted_at timestamptz NOT NULL DEFAULT now(),reviewed_at timestamptz,PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,material_id) REFERENCES app.materials,FOREIGN KEY(org_id,student_id) REFERENCES app.student_profiles,FOREIGN KEY(org_id,reviewer_id) REFERENCES app.memberships);
CREATE TABLE app.progress_records(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),student_id uuid NOT NULL,teacher_id uuid NOT NULL,department_name text NOT NULL,teacher_name_snapshot text NOT NULL,due_date date NOT NULL,content text NOT NULL,notes text NOT NULL DEFAULT '',source_system text,source_record_id text,state text NOT NULL CHECK(state IN ('unverified','not_started','in_progress','review_pending','completed')),row_version int NOT NULL DEFAULT 1,PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,student_id) REFERENCES app.student_profiles,FOREIGN KEY(org_id,teacher_id) REFERENCES app.teacher_profiles,UNIQUE(org_id,source_system,source_record_id));
CREATE TABLE app.lesson_slots(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),classroom_id uuid NOT NULL,teacher_id uuid NOT NULL,unit_id uuid,title text NOT NULL,starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,capacity int NOT NULL CHECK(capacity>0),booking_closes_at timestamptz NOT NULL,cancel_before_seconds int NOT NULL DEFAULT 86400 CHECK(cancel_before_seconds>=0),pending_ttl_seconds int NOT NULL DEFAULT 86400 CHECK(pending_ttl_seconds>0),state text NOT NULL CHECK(state IN ('open','closed','cancelled')),meeting_url text,PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,classroom_id,teacher_id) REFERENCES app.classroom_teachers(org_id,classroom_id,teacher_id),FOREIGN KEY(org_id,unit_id) REFERENCES app.units,CHECK(ends_at>starts_at),CHECK(booking_closes_at<=starts_at),CHECK(meeting_url IS NULL OR meeting_url LIKE 'https://%'),EXCLUDE USING gist(org_id WITH =, teacher_id WITH =,tstzrange(starts_at,ends_at,'[)') WITH &&) WHERE(state<>'cancelled'),EXCLUDE USING gist(org_id WITH =, classroom_id WITH =,tstzrange(starts_at,ends_at,'[)') WITH &&) WHERE(state<>'cancelled'));
CREATE TABLE app.reservations(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),slot_id uuid NOT NULL,student_id uuid NOT NULL,starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,status text NOT NULL CHECK(status IN ('pending','approved','rejected','cancelled','expired','removed')),expires_at timestamptz NOT NULL,reason text, idempotency_key uuid NOT NULL,row_version int NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,slot_id) REFERENCES app.lesson_slots,FOREIGN KEY(org_id,student_id) REFERENCES app.student_profiles,UNIQUE(org_id,student_id,idempotency_key),CHECK(ends_at>starts_at),EXCLUDE USING gist(org_id WITH =,student_id WITH =,tstzrange(starts_at,ends_at,'[)') WITH &&) WHERE(status IN ('pending','approved')));
CREATE UNIQUE INDEX reservation_one_active ON app.reservations(org_id,slot_id,student_id) WHERE status IN ('pending','approved');
CREATE INDEX reservation_slot_state ON app.reservations(org_id,slot_id,status,expires_at);
CREATE TABLE app.attendance(org_id uuid NOT NULL,slot_id uuid NOT NULL,student_id uuid NOT NULL,state text NOT NULL CHECK(state IN ('present','absent','late','excused')),recorded_by uuid NOT NULL,note text NOT NULL DEFAULT '',updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(org_id,slot_id,student_id),FOREIGN KEY(org_id,slot_id) REFERENCES app.lesson_slots,FOREIGN KEY(org_id,student_id) REFERENCES app.student_profiles,FOREIGN KEY(org_id,recorded_by) REFERENCES app.memberships);
CREATE TABLE app.audit_events(org_id uuid NOT NULL REFERENCES app.organizations,id uuid NOT NULL DEFAULT gen_random_uuid(),actor_id uuid,event_type text NOT NULL,entity_id uuid,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(org_id,id));
CREATE TABLE app.outbox(org_id uuid NOT NULL REFERENCES app.organizations,id uuid NOT NULL DEFAULT gen_random_uuid(),event_type text NOT NULL,entity_id uuid NOT NULL,payload jsonb NOT NULL,state text NOT NULL DEFAULT 'pending' CHECK(state IN ('pending','processing','delivered','failed')),attempts int NOT NULL DEFAULT 0,next_attempt_at timestamptz NOT NULL DEFAULT now(),locked_until timestamptz,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(org_id,id));
CREATE TABLE app.notifications(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),user_id uuid NOT NULL,event_id uuid NOT NULL,title text NOT NULL,body text NOT NULL,deep_link text NOT NULL,read_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,user_id) REFERENCES app.memberships,UNIQUE(org_id,user_id,event_id));
CREATE TABLE app.device_tokens(org_id uuid NOT NULL,user_id uuid NOT NULL,token_hash text NOT NULL,encrypted_token text NOT NULL,environment text NOT NULL CHECK(environment IN ('sandbox','production')),PRIMARY KEY(org_id,user_id,token_hash),FOREIGN KEY(org_id,user_id) REFERENCES app.memberships);
CREATE TABLE app.voice_sessions(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),user_id uuid NOT NULL,provider_session_id text,expires_at timestamptz NOT NULL,ended_at timestamptz,reserved_seconds int NOT NULL CHECK(reserved_seconds>0),consumed_seconds int CHECK(consumed_seconds>=0),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,user_id) REFERENCES app.memberships);
CREATE TABLE app.voice_actions(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),session_id uuid NOT NULL,user_id uuid NOT NULL,token_hash text NOT NULL,intent text NOT NULL CHECK(intent IN ('reserve','cancel')),payload jsonb NOT NULL,expires_at timestamptz NOT NULL,result jsonb,consumed_at timestamptz,PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,session_id) REFERENCES app.voice_sessions,FOREIGN KEY(org_id,user_id) REFERENCES app.memberships,UNIQUE(token_hash));
CREATE TABLE app.voice_tool_executions(org_id uuid NOT NULL,session_id uuid NOT NULL,call_id text NOT NULL,request_hash text NOT NULL,result jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(org_id,session_id,call_id),FOREIGN KEY(org_id,session_id) REFERENCES app.voice_sessions);
CREATE TABLE app.import_jobs(org_id uuid NOT NULL,id uuid NOT NULL DEFAULT gen_random_uuid(),created_by uuid NOT NULL,source_system text NOT NULL,object_key text NOT NULL,mapping jsonb NOT NULL,state text NOT NULL CHECK(state IN ('uploaded','validated','committing','completed','failed','rolled_back')),summary jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(org_id,id),FOREIGN KEY(org_id,created_by) REFERENCES app.memberships);
CREATE TABLE app.import_items(org_id uuid NOT NULL,job_id uuid NOT NULL,row_number int NOT NULL,entity_id uuid,entity_kind text NOT NULL,before_data jsonb,after_data jsonb,error text,committed_version int,PRIMARY KEY(org_id,job_id,row_number),FOREIGN KEY(org_id,job_id) REFERENCES app.import_jobs);
CREATE TABLE app.web_sessions(id text PRIMARY KEY,user_id uuid NOT NULL REFERENCES app.users,encrypted_provider_tokens text NOT NULL,csrf_hash text NOT NULL,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE FUNCTION app.guard_classroom_capacity() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE cap int;used int; BEGIN
 PERFORM 1 FROM app.classrooms WHERE org_id=NEW.org_id AND id=NEW.classroom_id FOR UPDATE;
 IF TG_OP='UPDATE' AND OLD.classroom_id<>NEW.classroom_id THEN RAISE EXCEPTION 'CLASSROOM_TRANSFER_REQUIRES_SERVICE'; END IF;
 IF NEW.active THEN SELECT capacity INTO cap FROM app.classrooms WHERE org_id=NEW.org_id AND id=NEW.classroom_id AND NOT archived;
 SELECT count(*) INTO used FROM app.student_profiles WHERE org_id=NEW.org_id AND classroom_id=NEW.classroom_id AND active AND id<>NEW.id;
 IF cap IS NULL OR used>=cap THEN RAISE EXCEPTION 'CLASSROOM_FULL'; END IF; END IF; RETURN NEW; END $$;
CREATE TRIGGER classroom_capacity BEFORE INSERT OR UPDATE ON app.student_profiles FOR EACH ROW EXECUTE FUNCTION app.guard_classroom_capacity();
CREATE FUNCTION app.guard_slot_update() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF EXISTS(SELECT 1 FROM app.reservations WHERE org_id=OLD.org_id AND slot_id=OLD.id AND status IN ('pending','approved')) AND (NEW.starts_at<>OLD.starts_at OR NEW.ends_at<>OLD.ends_at OR NEW.teacher_id<>OLD.teacher_id OR NEW.classroom_id<>OLD.classroom_id OR NEW.state='cancelled' OR NEW.capacity<OLD.capacity) THEN RAISE EXCEPTION 'ACTIVE_RESERVATIONS'; END IF; RETURN NEW; END $$;
CREATE TRIGGER slot_active_guard BEFORE UPDATE ON app.lesson_slots FOR EACH ROW EXECUTE FUNCTION app.guard_slot_update();
CREATE FUNCTION app.guard_version() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE o uuid;v uuid;BEGIN
 IF TG_OP='DELETE' THEN o:=OLD.org_id;v:=OLD.program_version_id;ELSE o:=NEW.org_id;v:=NEW.program_version_id;END IF;
 IF EXISTS(SELECT 1 FROM app.program_versions WHERE org_id=o AND id=v AND state<>'draft') THEN RAISE EXCEPTION 'PUBLISHED_VERSION_IMMUTABLE';END IF;
 IF TG_OP='DELETE' THEN RETURN OLD;ELSE RETURN NEW;END IF; END $$;
CREATE TRIGGER unit_version_guard BEFORE INSERT OR UPDATE OR DELETE ON app.units FOR EACH ROW EXECUTE FUNCTION app.guard_version();
CREATE VIEW app.enrollment_progress WITH(security_invoker=true) AS
SELECT e.org_id,e.id AS enrollment_id,e.student_id,e.program_version_id,e.due_on,
 round(100.0*sum(CASE WHEN p.state='completed' THEN u.weight ELSE 0 END)/nullif(sum(u.weight),0)) AS progress_percent
FROM app.enrollments e LEFT JOIN app.units u ON u.org_id=e.org_id AND u.program_version_id=e.program_version_id AND u.required
LEFT JOIN app.unit_progress p ON p.org_id=e.org_id AND p.enrollment_id=e.id AND p.unit_id=u.id
GROUP BY e.org_id,e.id,e.student_id,e.program_version_id,e.due_on;
DO $$ DECLARE t record; BEGIN FOR t IN SELECT tablename FROM pg_tables WHERE schemaname='app' AND tablename NOT IN ('organizations','users','web_sessions') LOOP
 EXECUTE format('ALTER TABLE app.%I ENABLE ROW LEVEL SECURITY',t.tablename);
 EXECUTE format('ALTER TABLE app.%I FORCE ROW LEVEL SECURITY',t.tablename);
 EXECUTE format('CREATE POLICY tenant_scope ON app.%I USING(org_id=app.org_id()) WITH CHECK(org_id=app.org_id())',t.tablename);
 END LOOP; END $$;
REVOKE ALL ON SCHEMA app FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA app FROM PUBLIC;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA app FROM PUBLIC;
COMMIT;
