/**
 * Private R2 object storage for materials, submissions, import files and exports (owned by the learning module).
 *
 * - Presigned URLs (client upload PUT, download GET) are AWS SigV4 query-signed URLs against the S3-compatible
 *   endpoint (`R2_S3_ENDPOINT`, e.g. https://<account>.r2.cloudflarestorage.com, path-style `/<bucket>/<key>`).
 *   The same code works against the local S3 service (SeaweedFS) for development and tests.
 * - Server-side reads/writes use the `R2_MATERIALS` binding when the endpoint is Cloudflare R2 itself (the binding
 *   and `R2_BUCKET_NAME` must name the same bucket); for any other S3-compatible endpoint (SeaweedFS locally) every operation
 *   uses the S3 API so presigned uploads and server reads always hit the same store. Copies always use S3
 *   CopyObject (server-side, no data transfer through the Worker).
 * Not configured (any of endpoint/bucket/key id/secret missing) → null; callers respond NOT_CONFIGURED.
 */
import { AwsClient } from "aws4fetch";
import type { Bindings, Config } from "../env";
import { ApiError } from "../http/errors";

export interface ObjectStorage {
  /** Short-lived presigned PUT URL for direct client upload into the quarantine prefix. */
  presignPut(key: string, contentType: string, sizeBytes: number, expiresSeconds: number): Promise<{ url: string; headers: Record<string, string> }>;
  /** Short-lived presigned GET URL (served only after the API has authorised the caller). */
  presignGet(key: string, expiresSeconds: number, opts?: { filename?: string; contentType?: string; disposition?: "inline" | "attachment" }): Promise<string>;
  head(key: string): Promise<{ size: number; contentType: string | null } | null>;
  /** Reads a byte range (used for magic-byte verification). Returns fewer bytes when the object is shorter. */
  readRange(key: string, offset: number, length: number): Promise<Uint8Array | null>;
  get(key: string): Promise<ReadableStream<Uint8Array> | null>;
  put(key: string, body: ReadableStream<Uint8Array> | Uint8Array | string, contentType: string): Promise<void>;
  copy(fromKey: string, toKey: string): Promise<void>;
  delete(key: string): Promise<void>;
}

export interface S3StorageOptions {
  endpoint: string;
  bucket: string;
  accessKeyId: string;
  secretAccessKey: string;
  /** Optional R2 binding for server-side operations (used only when the endpoint is Cloudflare R2). */
  binding?: R2Bucket | null;
  fetchImpl?: typeof fetch;
  timeoutMs?: number;
}

const MAX_PRESIGN_SECONDS = 7 * 24 * 3600;

/** RFC 6266 / RFC 5987 Content-Disposition with an ASCII fallback and a UTF-8 filename. */
export function contentDisposition(disposition: "inline" | "attachment", filename?: string): string {
  if (!filename) return disposition;
  const ascii = filename.replace(/[^\x20-\x7e]/g, "_").replace(/["\\]/g, "_");
  const encoded = encodeURIComponent(filename).replace(/['()*]/g, (ch) => `%${ch.charCodeAt(0).toString(16).toUpperCase()}`);
  return `${disposition}; filename="${ascii}"; filename*=UTF-8''${encoded}`;
}

function assertKey(key: string): void {
  // Keys are generated by the API (prefix/<org uuid>/<uuid>); reject anything that could escape the prefix.
  if (!/^[a-z]+(\/[A-Za-z0-9._-]+)+$/.test(key) || key.includes("..")) throw new Error("Invalid object key");
}

export function isR2Endpoint(endpoint: string): boolean {
  try {
    return new URL(endpoint).hostname.endsWith(".r2.cloudflarestorage.com");
  } catch {
    return false;
  }
}

export function createS3Storage(opts: S3StorageOptions): ObjectStorage {
  const endpoint = opts.endpoint.replace(/\/+$/, "");
  const r2 = isR2Endpoint(endpoint);
  const client = new AwsClient({
    accessKeyId: opts.accessKeyId,
    secretAccessKey: opts.secretAccessKey,
    service: "s3",
    region: r2 ? "auto" : "us-east-1",
    retries: 2,
  });
  const binding = r2 ? (opts.binding ?? null) : null;
  const doFetch = opts.fetchImpl ?? fetch;
  const timeoutMs = opts.timeoutMs ?? 30_000;

  const objectUrl = (key: string) => {
    assertKey(key);
    return `${endpoint}/${encodeURIComponent(opts.bucket)}/${key.split("/").map(encodeURIComponent).join("/")}`;
  };

  async function send(url: string, init: { method: string; headers?: Record<string, string>; body?: BodyInit | null }): Promise<Response> {
    const signed = await client.sign(url, { method: init.method, headers: init.headers ?? {}, body: init.body ?? null });
    const ac = new AbortController();
    const timer = setTimeout(() => ac.abort(), timeoutMs);
    try {
      return await doFetch(signed, { signal: ac.signal });
    } catch (e) {
      throw new ApiError("STORAGE_UNAVAILABLE", { cause: e });
    } finally {
      clearTimeout(timer);
    }
  }

  async function expectOk(res: Response, allow404 = false): Promise<boolean> {
    if (res.ok) return true;
    if (allow404 && res.status === 404) {
      await res.body?.cancel();
      return false;
    }
    await res.body?.cancel();
    throw new ApiError("STORAGE_UNAVAILABLE", { details: { storage_status: res.status } });
  }

  async function presign(key: string, method: "GET" | "PUT", expiresSeconds: number, headers: Record<string, string>, query: Record<string, string> = {}): Promise<string> {
    const seconds = Math.max(1, Math.min(MAX_PRESIGN_SECONDS, Math.floor(expiresSeconds)));
    const url = new URL(objectUrl(key));
    for (const [k, v] of Object.entries(query)) url.searchParams.set(k, v);
    url.searchParams.set("X-Amz-Expires", String(seconds));
    const signed = await client.sign(url.toString(), { method, headers, aws: { signQuery: true, allHeaders: true } });
    return signed.url;
  }

  return {
    async presignPut(key, contentType, sizeBytes, expiresSeconds) {
      // Content-Type and Content-Length are signed: the client must upload exactly the declared type and size.
      const headers = { "content-type": contentType, "content-length": String(sizeBytes) };
      const url = await presign(key, "PUT", expiresSeconds, headers);
      return { url, headers: { "Content-Type": contentType } };
    },
    async presignGet(key, expiresSeconds, o = {}) {
      const query: Record<string, string> = {};
      if (o.contentType) query["response-content-type"] = o.contentType;
      query["response-content-disposition"] = contentDisposition(o.disposition ?? "inline", o.filename);
      query["response-cache-control"] = "private, no-store";
      return presign(key, "GET", expiresSeconds, {}, query);
    },
    async head(key) {
      if (binding) {
        assertKey(key);
        const obj = await binding.head(key);
        return obj ? { size: obj.size, contentType: obj.httpMetadata?.contentType ?? null } : null;
      }
      const res = await send(objectUrl(key), { method: "HEAD" });
      if (!(await expectOk(res, true))) return null;
      const size = Number(res.headers.get("content-length") ?? "NaN");
      if (!Number.isFinite(size)) throw new ApiError("STORAGE_UNAVAILABLE");
      return { size, contentType: res.headers.get("content-type") };
    },
    async readRange(key, offset, length) {
      if (length <= 0) return new Uint8Array(0);
      if (binding) {
        assertKey(key);
        const obj = await binding.get(key, { range: { offset, length } });
        return obj ? new Uint8Array(await obj.arrayBuffer()) : null;
      }
      const res = await send(objectUrl(key), { method: "GET", headers: { range: `bytes=${offset}-${offset + length - 1}` } });
      if (res.status === 416) {
        await res.body?.cancel();
        return new Uint8Array(0);
      }
      if (!(await expectOk(res, true))) return null;
      const bytes = new Uint8Array(await res.arrayBuffer());
      // A server that ignores Range returns the whole object; keep only the requested window.
      return res.status === 206 ? bytes : bytes.subarray(offset, offset + length);
    },
    async get(key) {
      if (binding) {
        assertKey(key);
        const obj = await binding.get(key);
        return obj ? obj.body : null;
      }
      const res = await send(objectUrl(key), { method: "GET" });
      if (!(await expectOk(res, true))) return null;
      return res.body;
    },
    async put(key, body, contentType) {
      if (binding) {
        assertKey(key);
        await binding.put(key, body, { httpMetadata: { contentType } });
        return;
      }
      let payload: BodyInit;
      if (typeof body === "string") payload = body;
      else if (body instanceof Uint8Array) payload = body;
      else payload = new Uint8Array(await new Response(body).arrayBuffer());
      const res = await send(objectUrl(key), { method: "PUT", headers: { "content-type": contentType }, body: payload });
      await expectOk(res);
      await res.body?.cancel();
    },
    async copy(fromKey, toKey) {
      assertKey(fromKey);
      const source = `/${encodeURIComponent(opts.bucket)}/${fromKey.split("/").map(encodeURIComponent).join("/")}`;
      const res = await send(objectUrl(toKey), { method: "PUT", headers: { "x-amz-copy-source": source } });
      await expectOk(res);
      // CopyObject may report errors in a 200 body; confirm the copy exists before the source is removed.
      const text = await res.text();
      if (/<Error>/.test(text)) throw new ApiError("STORAGE_UNAVAILABLE");
    },
    async delete(key) {
      if (binding) {
        assertKey(key);
        await binding.delete(key);
        return;
      }
      const res = await send(objectUrl(key), { method: "DELETE" });
      if (res.status === 404) {
        await res.body?.cancel();
        return;
      }
      await expectOk(res);
      await res.body?.cancel();
    },
  };
}

export function createObjectStorage(env: Bindings, _config: Config): ObjectStorage | null {
  const { R2_S3_ENDPOINT, R2_BUCKET_NAME, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY } = env;
  if (!R2_S3_ENDPOINT || !R2_BUCKET_NAME || !R2_ACCESS_KEY_ID || !R2_SECRET_ACCESS_KEY) return null;
  return createS3Storage({
    endpoint: R2_S3_ENDPOINT,
    bucket: R2_BUCKET_NAME,
    accessKeyId: R2_ACCESS_KEY_ID,
    secretAccessKey: R2_SECRET_ACCESS_KEY,
    binding: env.R2_MATERIALS ?? null,
  });
}
