const {PGlite}=require('@electric-sql/pglite');const {btree_gist}=require('@electric-sql/pglite/contrib/btree_gist');const fs=require('fs');
const P=require('path').resolve(__dirname,'..');
(async()=>{const db=new PGlite({extensions:{btree_gist}});const results=[];let asserts=0;
function ok(name,value){if(!value)throw Error(name);results.push({name,result:'passed'});asserts++}
async function fails(name,fn,code){try{await fn();throw Error('Unexpected success')}catch(e){if(!String(e.message).includes(code))throw e;ok(name,true)}}
for(const f of ['001_schema.sql','002_reservations.sql','003_supporting_workflows.sql']){await db.exec(fs.readFileSync(P+'/db/'+f,'utf8'));ok('apply '+f,true)}
const o='00000000-0000-0000-0000-000000000001',o2='00000000-0000-0000-0000-000000000002',t='10000000-0000-0000-0000-000000000001',s1='20000000-0000-0000-0000-000000000001',s2='20000000-0000-0000-0000-000000000002',a='30000000-0000-0000-0000-000000000001',c='40000000-0000-0000-0000-000000000001',slot='50000000-0000-0000-0000-000000000001',slot2='50000000-0000-0000-0000-000000000002',v='60000000-0000-0000-0000-000000000001',pr='70000000-0000-0000-0000-000000000001',u1='80000000-0000-0000-0000-000000000001',u2='80000000-0000-0000-0000-000000000002',e1='90000000-0000-0000-0000-000000000001';
await db.exec(`INSERT INTO app.organizations(id,name) VALUES('${o}','テスト組織'),('${o2}','別組織');INSERT INTO app.users(id,display_name,email) VALUES('${t}','講師','teacher@example.invalid'),('${s1}','受講者1','s1@example.invalid'),('${s2}','受講者2','s2@example.invalid'),('${a}','管理者','admin@example.invalid');INSERT INTO app.memberships VALUES('${o}','${t}','teacher',true),('${o}','${s1}','student',true),('${o}','${s2}','student',true),('${o}','${a}','admin',true);INSERT INTO app.teacher_profiles(org_id,id,teacher_number) VALUES('${o}','${t}','T001');INSERT INTO app.classrooms(org_id,id,name,capacity,starts_on,ends_on) VALUES('${o}','${c}','Aクラス',2,current_date,current_date+90);INSERT INTO app.classroom_teachers VALUES('${o}','${c}','${t}',true);INSERT INTO app.student_profiles(org_id,id,employee_number,department_name,joined_on,classroom_id,teacher_id,training_starts_on,training_due_on) VALUES('${o}','${s1}','E001','開発部',current_date,'${c}','${t}',current_date,current_date+90),('${o}','${s2}','E002','開発部',current_date,'${c}','${t}',current_date,current_date+90);INSERT INTO app.lesson_slots(org_id,id,classroom_id,teacher_id,title,starts_at,ends_at,capacity,booking_closes_at,state) VALUES('${o}','${slot}','${c}','${t}','IT基礎',now()+interval '4 days',now()+interval '4 days 90 minutes',1,now()+interval '3 days','open'),('${o}','${slot2}','${c}','${t}','面談',now()+interval '5 days',now()+interval '5 days 60 minutes',1,now()+interval '4 days','open');INSERT INTO app.programs(org_id,id,name) VALUES('${o}','${pr}','基礎研修');INSERT INTO app.program_versions(org_id,id,program_id,version_number,state) VALUES('${o}','${v}','${pr}',1,'draft');INSERT INTO app.units(org_id,id,program_version_id,title,position,weight) VALUES('${o}','${u1}','${v}','単元1',0,20),('${o}','${u2}','${v}','単元2',1,80);INSERT INTO app.enrollments(org_id,id,student_id,program_version_id,due_on) VALUES('${o}','${e1}','${s1}','${v}',current_date+90);INSERT INTO app.unit_progress VALUES('${o}','${e1}','${v}','${u1}','completed',now(),1);UPDATE app.program_versions SET state='published' WHERE id='${v}';CREATE ROLE arms_test;GRANT USAGE ON SCHEMA app TO arms_test;GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA app TO arms_test;GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA app TO arms_test;SET ROLE arms_test;`);
async function actor(id,org=o){await db.query(`SELECT set_config('app.org_id',$1,false),set_config('app.user_id',$2,false)`,[org,id])}
await actor(s1);let created=(await db.query('SELECT app.create_reservation($1,$2) AS r',[slot,'aaaaaaaa-0000-0000-0000-000000000001'])).rows[0].r;ok('student reservation pending',created.status==='pending');
let repeat=(await db.query('SELECT app.create_reservation($1,$2) AS r',[slot,'aaaaaaaa-0000-0000-0000-000000000001'])).rows[0].r;ok('idempotent same reservation',repeat.id===created.id);
await fails('same key different slot rejected',()=>db.query('SELECT app.create_reservation($1,$2)',[slot2,'aaaaaaaa-0000-0000-0000-000000000001']),'IDEMPOTENCY_CONFLICT');
await actor(s2);await fails('seat capacity rejected',()=>db.query('SELECT app.create_reservation($1,$2)',[slot,'aaaaaaaa-0000-0000-0000-000000000002']),'SLOT_FULL');
await fails('student cannot approve',()=>db.query("SELECT app.change_reservation($1,'approve',NULL,1)",[created.id]),'FORBIDDEN');
await actor(t);let approved=(await db.query("SELECT app.change_reservation($1,'approve',NULL,1) AS r",[created.id])).rows[0].r;ok('assigned teacher approve',approved.status==='approved');
await fails('stale version refused',()=>db.query("SELECT app.change_reservation($1,'remove','テスト',1)",[created.id]),'VERSION_CONFLICT');
await fails('slot update with active booking refused',()=>db.query("UPDATE app.lesson_slots SET starts_at=starts_at+interval '5 minutes' WHERE id=$1",[slot]),'ACTIVE_RESERVATIONS');
await actor(s1);let cancelled=(await db.query("SELECT app.change_reservation($1,'cancel',NULL,2) AS r",[created.id])).rows[0].r;ok('owner cancel',cancelled.status==='cancelled');
await actor(s2);let second=(await db.query('SELECT app.create_reservation($1,$2) AS r',[slot,'aaaaaaaa-0000-0000-0000-000000000002'])).rows[0].r;ok('seat restored after cancel',second.status==='pending');
await actor(t);await fails('reject requires reason',()=>db.query("SELECT app.change_reservation($1,'reject','',1)",[second.id]),'REASON_REQUIRED');
let rejected=(await db.query("SELECT app.change_reservation($1,'reject','日程変更',1) AS r",[second.id])).rows[0].r;ok('teacher reject with reason',rejected.status==='rejected');
let removed=(await db.query("SELECT app.change_reservation($1,'remove','申請整理',2) AS r",[second.id])).rows[0].r;ok('soft removal retains row',removed.status==='removed');
const audit=(await db.query('SELECT count(*)::int n FROM app.audit_events')).rows[0].n;const outbox=(await db.query('SELECT count(*)::int n FROM app.outbox')).rows[0].n;ok('mutation audit and outbox atomic count',audit===6&&outbox===6);
const progress=(await db.query('SELECT progress_percent FROM app.enrollment_progress')).rows[0].progress_percent;ok('weighted progress 20 percent',Number(progress)===20);
await fails('published unit mutation rejected',()=>db.query('UPDATE app.units SET weight=30 WHERE id=$1',[u1]),'PUBLISHED_VERSION_IMMUTABLE');
await actor(a);await fails('classroom capacity cannot shrink below active students',()=>db.query('UPDATE app.classrooms SET capacity=1 WHERE id=$1',[c]),'CAPACITY_BELOW_ENROLLMENT');await fails('classroom with active students cannot archive',()=>db.query('UPDATE app.classrooms SET archived=true WHERE id=$1',[c]),'CLASSROOM_HAS_STUDENTS');await actor(a,o2);ok('tenant RLS hides foreign students',(await db.query('SELECT count(*)::int n FROM app.student_profiles')).rows[0].n===0);
await fails('tenant RLS insert denied',()=>db.query(`INSERT INTO app.programs(org_id,name) VALUES($1,'外部')`,[o]),'row-level security');
await actor(s1);await db.query(`UPDATE app.reservations SET status='pending',expires_at=now()-interval '1 second' WHERE id=$1`,[created.id]);await db.query('SELECT app.expire_slot($1)',[slot]);ok('expired pending transitions',(await db.query('SELECT status FROM app.reservations WHERE id=$1',[created.id])).rows[0].status==='expired');
fs.writeFileSync(P+'/verification/db-tests.json',JSON.stringify({runtime:'PGlite PostgreSQL WASM, btree_gist',tests:results,limitations:['実PostgreSQL複数接続の同時実行・Hyperdrive・実API・iOSは未実行。'],assertions:asserts},null,2));await db.close();console.log('DB checks passed',asserts);})().catch(e=>{console.error(e);process.exit(1)});
