/** POST /exports/progress and GET /exports/{id} (WEB-11 CSV/PDF出力). */
import { Hono } from "hono";
import { ExportInput, zonedDateString } from "@arms/contracts";
import type { AppEnv } from "../../context";
import { actorTx } from "../../context";
import { sql } from "../../db/sql";
import { requireRole } from "../../auth/middleware";
import { ApiError, fail } from "../../http/errors";
import { ok } from "../../http/respond";
import { pathId, readBody } from "../../http/validation";
import {
  EXPORT_COLUMNS,
  EXPORT_MAX_ROWS,
  EXPORT_SYNC_ROWS,
  countRecords,
  exportDto,
  filtersOf,
  insertExportJob,
  loadExportRecords,
  markExportFailed,
  markExportReady,
  renderExport,
  type ExportJobRow,
} from "../../domain/learning/exports";

export const exportRoutes = new Hono<AppEnv>();

/**
 * POST /exports/progress — same filters and teacher scope as GET /progress-records. Up to 500 rows the file is
 * generated immediately (state ready); larger exports are generated by the learning cron (state pending).
 * Rows are read in a short transaction; rendering and the object-storage upload happen outside it.
 */
exportRoutes.post("/exports/progress", requireRole("admin", "teacher"), async (c) => {
  const actor = c.get("actor");
  const deps = c.get("deps");
  const input = await readBody(c, ExportInput);
  const storage = deps.integrations.storage;
  if (!storage) fail("NOT_CONFIGURED");
  const now = deps.now();
  const today = zonedDateString(now, actor.timezone);
  const filters = filtersOf(input);
  const { job, records } = await actorTx(c, async (tx) => {
    const n = await countRecords(tx, actor, filters, today);
    if (n > EXPORT_MAX_ROWS) fail("EXPORT_TOO_LARGE");
    const sync = n <= EXPORT_SYNC_ROWS;
    const created = await insertExportJob(tx, actor, input, n, sync);
    return { job: created, records: sync ? await loadExportRecords(tx, actor, filters, now) : null };
  });
  if (!records) return ok(c, await exportDto(job, storage, now));
  try {
    const file = await renderExport(storage, job, actor, records, now);
    const ready = await actorTx(c, (tx) => markExportReady(tx, actor, job, file));
    return ok(c, await exportDto(ready ?? job, storage, now));
  } catch (e) {
    const code = e instanceof ApiError ? e.code : "INTERNAL";
    await actorTx(c, (tx) => markExportFailed(tx, actor.orgId, job.id, code));
    throw e;
  }
});

/** GET /exports/{id} — only the user who requested the export; ready files get a fresh 5-minute URL. */
exportRoutes.get("/exports/:id", requireRole("admin", "teacher"), async (c) => {
  const actor = c.get("actor");
  const id = pathId(c);
  const job = await actorTx(c, (tx) =>
    tx.maybeOne<ExportJobRow>(sql`SELECT ${EXPORT_COLUMNS} FROM app.export_jobs WHERE org_id = ${actor.orgId} AND id = ${id} AND user_id = ${actor.userId}`),
  );
  if (!job) fail("NOT_FOUND");
  const deps = c.get("deps");
  if (job.state === "ready" && !deps.integrations.storage) throw new ApiError("NOT_CONFIGURED");
  return ok(c, await exportDto(job, deps.integrations.storage, deps.now()));
});
